# 1 基本使用方法

In [1]:
import torch
torch.__version__

'1.9.1'

## 创建一个矩阵

In [2]:
x = torch.empty(5,3)
x

tensor([[ 6.2582e-42,  1.8776e-39,  5.1252e-36],
        [ 4.6894e+27,  2.6706e-41,  1.0877e-38],
        [ 4.8872e-26,  2.5353e+30,  3.3631e-44],
        [ 2.6347e-41,  1.2990e-38, -1.7779e-37],
        [ 2.5353e+30,  1.1070e-43,  2.8275e+32]])

## 创建一个随机矩阵

In [3]:
x = torch.rand(5,3)
x

tensor([[0.0831, 0.1800, 0.4176],
        [0.3979, 0.3776, 0.1933],
        [0.1880, 0.8298, 0.5212],
        [0.1913, 0.7902, 0.2759],
        [0.1387, 0.0664, 0.5123]])

## 初始化一个全零的矩阵

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])